### ISSUE TITLE
not compatible with node 16

### ISSUE THREAD

**Issue by applemate** [prgm-dev/sveltekit-progress-bar#1]
<img width="456" alt="Screenshot 2023-03-04 at 12 08 16 PM" src="https://user-images.githubusercontent.com/538657/222877100-36f9ea0f-2f69-4572-8dee-74eb532e5316.png">

**Comment by allezxandre** [comment]
Node 16 was in maintenance mode at the time this package was released (see [Node’s release schedule](https://github.com/nodejs/release#release-schedule)), and it has now reached its end-of-life (see [this annoucement](https://nodejs.org/en/blog/announcements/nodejs16-eol)).

As such, support for Node 16 is not planned.
