### ISSUE TITLE
Support View Transition API

### ISSUE THREAD

**Issue by frederichoule** [prgm-dev/sveltekit-progress-bar#3]
The progressbar disappear during a view transition event. An easy fix would be to add a `view-transition-name: progressbar;` to its styling. I can submit a PR later if you want.

More infos:
- https://developer.chrome.com/docs/web-platform/view-transitions/
- https://svelte.dev/blog/view-transitions

**Comment by 128keaton** [comment]
I second this

**Comment by allezxandre** [comment]
Thank you for the report, I'll try and add this in a later update to support Svelte 5

**Comment by allezxandre** [comment]
FYI, this is now included in the upcoming Svelte 5 version that is now in beta under the [3.0.0-next.1](https://www.npmjs.com/package/@prgm/sveltekit-progress-bar/v/3.0.0-next.1) tag.
