### ISSUE TITLE
Having navigation fail/cancel leaves progressbar hanging

### ISSUE THREAD

**Issue by bertmad3400** [prgm-dev/sveltekit-progress-bar#5]
As this library doesn't use the "complete" promise from beforeNavigate, but instead uses afterNavigate to "finish" the progress-bar, it fails to take into account navigations which fails or are cancelled. I would imagine the most common occurrence of this (which is the one I ran into) is cancelling the navigation during beforeNavigate using the cancel param, which will just leave the progress-bar hanging giving an impression of a broken app

**Comment by allezxandre** [comment]
Implemented a fix in the linked PR. 

Feel free to try it out using the beta [3.0.1-next.1](https://www.npmjs.com/package/@prgm/sveltekit-progress-bar/v/3.0.1-next.1) release

**Comment by mxz7** [comment]
I'm still getting this issue when there's a redirect in a page load
